// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doanasp.Data;

namespace doanasp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20211208025422_deletongtien")]
    partial class deletongtien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("doanasp.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("capnhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("mahoadon1")
                        .HasColumnType("int");

                    b.Property<int?>("masanpham1")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<int>("tongtien")
                        .HasColumnType("int");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("mahoadon1");

                    b.HasIndex("masanpham1");

                    b.ToTable("chiTietHoaDons");
                });

            modelBuilder.Entity("doanasp.Models.GioHang", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("makhachhang1")
                        .HasColumnType("int");

                    b.Property<int?>("masanpham1")
                        .HasColumnType("int");

                    b.Property<string>("soluong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("makhachhang1");

                    b.HasIndex("masanpham1");

                    b.ToTable("gioHangs");
                });

            modelBuilder.Entity("doanasp.Models.HoaDon", b =>
                {
                    b.Property<int>("mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("accountmakhachhang")
                        .HasColumnType("int");

                    b.Property<DateTime>("capnhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("makhachhang")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaylap")
                        .HasColumnType("datetime2");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("mahoadon");

                    b.HasIndex("accountmakhachhang");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("doanasp.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tensanpham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("maloai");

                    b.ToTable("loaiSanPhams");
                });

            modelBuilder.Entity("doanasp.Models.SanPham", b =>
                {
                    b.Property<int>("masanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("chatlieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("giaban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hinhanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kichthuoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("maloai1")
                        .HasColumnType("int");

                    b.Property<string>("mausac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("motasanpham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noisanxuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("soluongton")
                        .HasColumnType("int");

                    b.Property<string>("tensanpham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("masanpham");

                    b.HasIndex("maloai1");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("doanasp.Models.account", b =>
                {
                    b.Property<int>("makhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hovaten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phuongthucdangnhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendangnhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("trangthai")
                        .HasColumnType("int");

                    b.HasKey("makhachhang");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("doanasp.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("doanasp.Models.HoaDon", "mahoadon")
                        .WithMany("chiTietHoaDons")
                        .HasForeignKey("mahoadon1");

                    b.HasOne("doanasp.Models.SanPham", "masanpham")
                        .WithMany("chiTietHoaDons")
                        .HasForeignKey("masanpham1");
                });

            modelBuilder.Entity("doanasp.Models.GioHang", b =>
                {
                    b.HasOne("doanasp.Models.account", "makhachhang")
                        .WithMany("gioHangs")
                        .HasForeignKey("makhachhang1");

                    b.HasOne("doanasp.Models.SanPham", "masanpham")
                        .WithMany("gioHangs")
                        .HasForeignKey("masanpham1");
                });

            modelBuilder.Entity("doanasp.Models.HoaDon", b =>
                {
                    b.HasOne("doanasp.Models.account", null)
                        .WithMany("hoaDons")
                        .HasForeignKey("accountmakhachhang");
                });

            modelBuilder.Entity("doanasp.Models.SanPham", b =>
                {
                    b.HasOne("doanasp.Models.LoaiSanPham", "maloai")
                        .WithMany("sanPhams")
                        .HasForeignKey("maloai1");
                });
#pragma warning restore 612, 618
        }
    }
}
